name: ta_scanner

channels:
    - default

dependencies:
    - python=3.7
    - click
    - sqlalchemy
    - pandas >= 1.0.0
    - numpy
    - requests
    - pytz
    - matplotlib
    - seaborn
    - jupyterlab
    # dash apps resources
    - dash
    - dash-html-components
    - dash-renderer
    - dash-core-components
    - plotly
    # test resources
    - pytest
    - pip
    - black
    - pip:
        - twine 
        - ipdb
        - loguru
        - "--editable ."
